<?php

/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function sycamore_showtimes_theme($existing, $type, $theme, $path) {
  return [
    "paragraph__sycamore_showtimes" => [
      "template" => "paragraph--sycamore-showtimes",
      "base hook" => "paragraph",
      "variables" => ["data" => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph().
 */
function sycamore_showtimes_preprocess_paragraph__sycamore_showtimes(&$variables) {
  $paragraph_entity = $variables["paragraph"];
  $variables["data"] = ["sycamore_component_id" => $paragraph_entity->id()];
}

/**
 * Implements hook_help().
 */
function sycamore_showtimes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.sycamore_showtimes':
      $module_handler = \Drupal::service('module_handler');
      $module_path = $module_handler->getModule('sycamore_showtimes')->getPath();
      $contents = file_get_contents($module_path . '/README.md');
      $parseDown = new Parsedown();
      $output = $parseDown->text($contents);
      return $output;
  }
}
